name: Job Scraper (5 PM PT)

on:
  schedule:
    # 5 PM Pacific = 01:00 UTC when PST (UTC-8)
    - cron: "0 1 * * *"
    # 5 PM Pacific = 00:00 UTC when PDT (UTC-7)
    - cron: "0 0 * * *"
  # allow manual runs too
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # minimal fallback if reqs file goes missing
            pip install "python-jobspy==1.1.82" pandas streamlit \
                       "pydantic<3" requests beautifulsoup4 markdownify tls-client \
                       python-dotenv tzdata numpy==1.26.3
          fi

      - name: Run automation (sends email)
        env:
          # required mail creds (set as Actions secrets in repo settings)
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:   ${{ secrets.SMTP_PORT }}
          SMTP_USER:   ${{ secrets.SMTP_USER }}
          SMTP_PASS:   ${{ secrets.SMTP_PASS }}
          SMTP_FROM:   ${{ secrets.SMTP_FROM }}
          # optional JobSpy tuning
          JOBSPY_PROXIES:   ${{ secrets.JOBSPY_PROXIES }}
          JOBSPY_USER_AGENT: ${{ secrets.JOBSPY_USER_AGENT }}
        run: |
          set -e
          echo "▶️ Running profiles at $(date -u) UTC"
          python automation_runner.py --profile shazia
          python automation_runner.py --profile yoshitha
          python automation_runner.py --profile ruthvej
          echo "✅ All profiles completed"

      - name: Upload CSV artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: job-results-${{ github.run_id }}
          path: |
            automation_out/*.csv
            debug_runs/**/*.csv
          if-no-files-found: warn
